## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"

In [3]:
titanic=pd.read_csv(url)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# code here
titanic.groupby('Pclass')['Age'].mean().head()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [5]:
titanic.groupby('Pclass')['Age'].apply(lambda x: x.isna().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [6]:
# code here
def fill(group):
     group.fillna().mode()
     return group

In [7]:
titanic.groupby('Pclass')['Embarked'].transform(
    lambda x: x.fillna(x.mode()[0])
)

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [8]:
titanic.groupby(['Embarked', 'Pclass'])['Fare'].mean().round(2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

In [9]:
# code here
titanic.groupby('Embarked').apply(lambda group : group.groupby('Pclass')['Fare'].mean()).round(2)

Pclass         1      2      3
Embarked
C         104.72  25.36  11.21
Q          90.00  12.35  11.18
S          70.36  20.33  14.64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [10]:
# code here
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 50+ balls


> Chasing mean team batting in second inning

In [11]:
# code here
matches=pd.read_csv('ipl_deliveries.csv')
matches.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [12]:
matches[matches['innings']==2].groupby(['ID','batter'])['batsman_run'].sum().sort_values(ascending=False).head()

ID       batter
501206   PC Valthaty      120
501243   V Sehwag         119
1254061  SV Samson        119
1136620  SR Watson        117
336018   ST Jayasuriya    114
Name: batsman_run, dtype: int64

In [13]:
result = (matches[matches['innings'] == 2].groupby(['batter','ID']).agg(runs=('batsman_run', 'sum'),balls=('batsman_run', 'count') ).reset_index())
result['strike_rate'] = result['runs'] / result['balls'] * 100
result[result['balls'] > 50].sort_values('strike_rate', ascending=False).head(1)

             batter      ID  runs  balls  strike_rate
6042  ST Jayasuriya  336018   114     53    215.09434

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [14]:
# code here
matches.groupby(['batter','bowler'])['isWicketDelivery'].sum().sort_values(ascending=False).head(1)

batter     bowler
RG Sharma  SP Narine    8
Name: isWicketDelivery, dtype: int64

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [15]:
#code here
matches['batting']=matches[['batter', 'non-striker']].apply(lambda x: tuple(sorted (x)),axis=1)
matches.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,batting
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(JC Buttler, YBK Jaiswal)"

In [16]:
matches.groupby('batting')['batsman_run'].sum().sort_values(ascending=False).head(1)

batting
(AB de Villiers, V Kohli)    3040
Name: batsman_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [17]:
# code here
match=matches[['batter','non-striker','batting','total_run']]
match

             batter  non-striker                    batting  total_run
0       YBK Jaiswal   JC Buttler  (JC Buttler, YBK Jaiswal)          0
1       YBK Jaiswal   JC Buttler  (JC Buttler, YBK Jaiswal)          1
2        JC Buttler  YBK Jaiswal  (JC Buttler, YBK Jaiswal)          1
3       YBK Jaiswal   JC Buttler  (JC Buttler, YBK Jaiswal)          0
4       YBK Jaiswal   JC Buttler  (JC Buttler, YBK Jaiswal)          0
...             ...          ...                        ...        ...
225949      P Kumar     SB Joshi        (P Kumar, SB Joshi)          1
225950     SB Joshi      P Kumar        (P Kumar, SB Joshi)          1
225951      P Kumar     SB Joshi        (P Kumar, SB Joshi)          0
225952     SB Joshi      P Kumar        (P Kumar, SB Joshi)          1
225953     SB Joshi      P Kumar        (P Kumar, SB Joshi)          0

[225954 rows x 4 columns]

In [18]:
result=match.groupby('batting').agg(runs=('total_run','sum'),total_ball=('total_run','count')).reset_index()
result.head()

                             batting  runs  total_ball
0         (A Ashish Reddy, A Mishra)    40          31
1  (A Ashish Reddy, AA Jhunjhunwala)     4           5
2         (A Ashish Reddy, CL White)    13           9
3     (A Ashish Reddy, DB Ravi Teja)    10           7
4        (A Ashish Reddy, DJG Sammy)    45          34

In [19]:
result['batting_strike']=((result['runs']/result['total_ball'])*100).round(2)
result

                                batting  runs  total_ball  batting_strike
0            (A Ashish Reddy, A Mishra)    40          31          129.03
1     (A Ashish Reddy, AA Jhunjhunwala)     4           5           80.00
2            (A Ashish Reddy, CL White)    13           9          144.44
3        (A Ashish Reddy, DB Ravi Teja)    10           7          142.86
4           (A Ashish Reddy, DJG Sammy)    45          34          132.35
...                                 ...   ...         ...             ...
4254         (WD Parnell, Yuvraj Singh)    41          18          227.78
4255               (WP Saha, YK Pathan)    17           9          188.89
4256      (WPUJC Vaas, Y Venugopal Rao)    42          26          161.54
4257         (Y Nagar, Y Venugopal Rao)   147         138          106.52
4258        (YV Takawale, Yuvraj Singh)     1           3           33.33

[4259 rows x 4 columns]